---
# tasks file for ansible-role-rpcbind

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: install package for rpcbind on redhat
  yum: name="{{package_name}}" state=present
  when: ansible_os_family == 'RedHat'

- name: install package for rpcbind on Debian
  apt: name="{{package_name}}" state=present
  when: ansible_os_family == 'Debian'

- name: install package for rpcbind on suse
  zypper: name="{{package_name}}" state=present
  when: ansible_os_family == 'Suse'

- name: configure rpcbind service
  service:
    name: "{{service_name}}"
    state: "{{service_state}}"
    enabled: "{{service_enabled}}"


